import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ConvertPdf from './_convertPdf';


export default function Home() {
  
  const pdfUrl = "/pdfs/medicare-supplement-app.pdf";

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs Pdf to Text POC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          NextJs Pdf to Text
        </h1>
        
        <p className={styles.description}>
          We often need to show the text of a pdf inline within a web page.  This NextJs utility will convert a searchable pdf to html.
          This <a className={styles.link} href={pdfUrl} target="_blank" rel="noreferrer">searchable pdf</a> is rendered below.
        </p>

        <h2>Resources</h2>
        <ul>
            <li><a className={styles.link} href="https://www.npmjs.com/package/react-pdf" target="_blank" rel="noreferrer">react-pdf package</a></li>
            <li><a className={styles.link} href="https://mozilla.github.io/pdf.js/" target="_blank" rel="noreferrer">pdfjs</a></li>
            <li><a className={styles.link} href="https://github.com/markfulton3/hztl-nextjs-pdf-to-text" target="_blank" rel="noreferrer">Github</a></li>
        </ul>

        <ConvertPdf src={pdfUrl} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Horizontal Digital &copy;2022
        </a>
      </footer>
    </div>
  )
}
